import rover from './rover'
import drone from './drone'
import maze from './maze'
import ptz from './ptz'
import lamp from './lamp'
import claw from './claw'
import boat from './boat'
import spotlights from './spotlights'
import vacuum from './vacuum'
import tank from './tank'
import excavator from './excavator'
import forklift from './forklift'
import painter from './painter'
import gimbal from './gimbal'
import plane from './plane'
import slotcars from './slotcars'
import dog from './dog'
import sorting from './sorting'
import kart from './kart'
import helicopter from './helicopter'
import submarine from './submarine'
import smarthome from './smarthome'
import airhockey from './airhockey'
import pinball from './pinball'
import football from './football'
import marblerun from './marblerun'
import planetary from './planetary'
import telescope from './telescope'
import pendulum from './pendulum'
import trebuchet from './trebuchet'
import slider from './slider'
import jib from './jib'
import studio from './studio'
import arena from './arena'
import viewer from './viewer'
import arm5 from './arm5'
import so101 from './so101'
import six from './six'
import scara from './scara'
import delta from './delta'
import desk from './desk'
import octopus from './octopus'
import type { SoundProfile } from '../profile'

export const PROFILES: readonly SoundProfile[] = [rover, drone, maze, ptz, lamp, claw, boat, spotlights, vacuum, tank, excavator, forklift, painter, gimbal, plane, slotcars, dog, sorting, kart, helicopter, submarine, smarthome, airhockey, pinball, football, marblerun, planetary, telescope, pendulum, trebuchet, slider, jib, studio, arena, viewer, arm5, so101, six, scara, delta, desk, octopus]
export const profileOf = (id: string) => {
  const p = PROFILES.find(p => p.id === id)
  if (!p) throw new Error(`Missing sound profile: ${id}`)
  return p
}
