"""Outline the existing header lockup using its bundled OFL fonts. Requires fontTools with Brotli.

Run python scripts/link-lockup.py after changing the canonical mark or header typography.
The output is a standalone vector: no font download or nested image is needed to render it.
"""
from pathlib import Path
import re
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from fontTools.pens.svgPathPen import SVGPathPen

root = Path(__file__).resolve().parent.parent
mark = (root / 'public/logo-mark.svg').read_text(encoding='utf-8').strip()
lime = re.search(r'stroke="(#[0-9a-fA-F]{6})"', mark)[1].lower()
family = (root / 'src/family/family.css').read_text(encoding='utf-8')
strong = re.search(r"\[data-bb-product='obpal'\][^\n]*--bb-accent-strong: (#[0-9a-f]{6});", family)[1]
ink = re.search(r"\[data-bb-product='obpal'\][^\n]*--bb-accent-ink: (#[0-9a-f]{6});", family)[1]
fonts = {}

def text(text, family, weight, size, x, baseline, tracking, ink=None):
    key = (family, weight)
    if key not in fonts:
        font = TTFont(root / f'public/fonts/{family}-latin.woff2')
        fonts[key] = instantiateVariableFont(font, {'wght': weight}, inplace=True)
    font = fonts[key]
    glyphs, cmap = font.getGlyphSet(), font.getBestCmap()
    scale = size / font['head'].unitsPerEm
    paths = []
    for char in text:
        glyph = glyphs[cmap[ord(char)]]
        pen = SVGPathPen(glyphs)
        glyph.draw(pen)
        fill = f' fill="{ink}"' if ink else ''
        paths.append(f'<path{fill} transform="translate({x:.4f} {baseline}) scale({scale:.6f} {-scale:.6f})" d="{pen.getCommands()}"/>')
        x += glyph.width * scale + tracking
    return ''.join(paths), x

ob, x = text('ob', 'plus-jakarta-sans', 500, 21, 51, 27, -.63)
point, x = text('.', 'plus-jakarta-sans', 700, 21, x + .315, 27, -.63, lime)
pal, x = text('Pal', 'plus-jakarta-sans', 800, 21, x + .315, 27, -.63)
base = round(x, 4)
pill_x = base + 10
label, end = text('LINK', 'inter', 750, 10.5, pill_x + 9, 24, 1.26, lime)
width = round(end + 9, 4)
svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} 40" shape-rendering="geometricPrecision">
  <!-- Generated by scripts/link-lockup.py. Mark: public/logo-mark.svg; fonts: bundled OFL header faces. -->
  <view id="base" viewBox="0 0 {base} 40"/>
  <view id="base-light" viewBox="0 0 {base} 40"/>
  <view id="light" viewBox="0 0 {width} 40"/>
  <style>.wordmark{{fill:#f4f4f5}}#base-light:target~.wordmark,#light:target~.wordmark{{fill:#161616}}#base-light:target~.wordmark .brand-point path,#light:target~.wordmark .brand-point path{{fill:{strong}}}#light:target~.link-label path{{fill:{ink}}}</style>
  <svg width="40" height="40" viewBox="0 0 100 100">{mark[mark.index('>')+1:mark.rindex('</svg>')]}</svg>
  <g class="wordmark"><g opacity=".82">{ob}</g><g class="brand-point">{point}</g>{pal}</g>
  <rect x="{pill_x}" y="9" width="{width-pill_x}" height="22" rx="11" fill="{lime}" fill-opacity=".12" stroke="{lime}" stroke-opacity=".28"/>
  <g class="link-label">{label}</g>
</svg>
'''
(root / 'public/brand/obpal-link-lockup.svg').write_text(svg, encoding='utf-8')
print(f'Link lockup: {width} x 40; base {base} x 40')
